"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const SCATYPE_BITS_INTERNAL = {
    /* tslint:disable:object-literal-sort-keys */
    CONST: 0xF0,
    NULL: 0xFF,
    UNDEFINED: 0xFF,
    TRUE: 0xFF,
    FALSE: 0xFF,
    NAN: 0xFF,
    REF: 0xF0,
    REF_TRAILING_VALUE: 0xFF,
    NUMBER: 0xE0,
    INT: 0xF0,
    INT_TRAILING_VALUE: 0xFF,
    DOUBLE_TRAILING_VALUE: 0xFF,
    CACHABLE: 0x80,
    USE_CACHE: 0x81,
    OBJECT: 0xF0,
    REGEXP: 0xF0,
    REGEXP_TRAILING_FLAGS: 0xFE,
    REGEXP_GLOBAL_FLAG: 0xFA,
    REGEXP_MULTILINE_FLAG: 0xFC,
    ARRAY: 0xF0,
    ARRAY_EMPTY: 0xFE,
    ARRAY_MIXED: 0xFE,
    ARRAY_INT: 0xFE,
    ARRAY_DOUBLE: 0xFE,
    ARRAY_BOOL: 0xFE,
    STRING: 0xF0,
    STRING_TRAILING_LENGTH: 0xFE,
};
exports.SCATYPE_BITS = SCATYPE_BITS_INTERNAL;
function checkType(byte, type) {
    const ref = SCATYPE[type];
    return (byte & exports.SCATYPE_BITS[type]) === ref;
}
exports.checkType = checkType;
var SCATYPE;
(function (SCATYPE) {
    SCATYPE[SCATYPE["CONST"] = 0] = "CONST";
    SCATYPE[SCATYPE["UNDEFINED"] = 0] = "UNDEFINED";
    SCATYPE[SCATYPE["TRUE"] = 1] = "TRUE";
    SCATYPE[SCATYPE["FALSE"] = 3] = "FALSE";
    SCATYPE[SCATYPE["NULL"] = 2] = "NULL";
    SCATYPE[SCATYPE["NAN"] = 4] = "NAN";
    SCATYPE[SCATYPE["REF"] = 16] = "REF";
    SCATYPE[SCATYPE["REF_TRAILING_VALUE"] = 31] = "REF_TRAILING_VALUE";
    SCATYPE[SCATYPE["NUMBER"] = 32] = "NUMBER";
    SCATYPE[SCATYPE["INT"] = 32] = "INT";
    SCATYPE[SCATYPE["INT_TRAILING_VALUE"] = 47] = "INT_TRAILING_VALUE";
    SCATYPE[SCATYPE["DOUBLE_TRAILING_VALUE"] = 63] = "DOUBLE_TRAILING_VALUE";
    SCATYPE[SCATYPE["CACHABLE"] = 128] = "CACHABLE";
    SCATYPE[SCATYPE["USE_CACHE"] = 129] = "USE_CACHE";
    SCATYPE[SCATYPE["OBJECT"] = 144] = "OBJECT";
    SCATYPE[SCATYPE["REGEXP"] = 160] = "REGEXP";
    SCATYPE[SCATYPE["REGEXP_TRAILING_FLAGS"] = 174] = "REGEXP_TRAILING_FLAGS";
    SCATYPE[SCATYPE["REGEXP_GLOBAL_FLAG"] = 162] = "REGEXP_GLOBAL_FLAG";
    SCATYPE[SCATYPE["REGEXP_MULTILINE_FLAG"] = 164] = "REGEXP_MULTILINE_FLAG";
    SCATYPE[SCATYPE["ARRAY"] = 176] = "ARRAY";
    SCATYPE[SCATYPE["ARRAY_EMPTY"] = 178] = "ARRAY_EMPTY";
    SCATYPE[SCATYPE["ARRAY_MIXED"] = 180] = "ARRAY_MIXED";
    SCATYPE[SCATYPE["ARRAY_INT"] = 182] = "ARRAY_INT";
    SCATYPE[SCATYPE["ARRAY_DOUBLE"] = 184] = "ARRAY_DOUBLE";
    SCATYPE[SCATYPE["ARRAY_BOOL"] = 186] = "ARRAY_BOOL";
    SCATYPE[SCATYPE["STRING"] = 192] = "STRING";
    SCATYPE[SCATYPE["STRING_TRAILING_LENGTH"] = 206] = "STRING_TRAILING_LENGTH";
})(SCATYPE = exports.SCATYPE || (exports.SCATYPE = {}));
//# sourceMappingURL=common.js.map